
package com.monditech.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Consultas", targetNamespace = "http://webservices.monditech.com/", wsdlLocation = "http://remoto.dapi.com.br/SOAP%20Consulta%20VIEW%20Homologacao/Consultas.asmx?wsdl")
public class Consultas
    extends Service
{

    private final static URL CONSULTAS_WSDL_LOCATION;
    private final static WebServiceException CONSULTAS_EXCEPTION;
    private final static QName CONSULTAS_QNAME = new QName("http://webservices.monditech.com/", "Consultas");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://remoto.dapi.com.br/SOAP%20Consulta%20VIEW%20Homologacao/Consultas.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAS_WSDL_LOCATION = url;
        CONSULTAS_EXCEPTION = e;
    }

    public Consultas() {
        super(__getWsdlLocation(), CONSULTAS_QNAME);
    }

    public Consultas(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAS_QNAME, features);
    }

    public Consultas(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAS_QNAME);
    }

    public Consultas(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAS_QNAME, features);
    }

    public Consultas(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Consultas(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultasSoap
     */
    @WebEndpoint(name = "ConsultasSoap")
    public ConsultasSoap getConsultasSoap() {
        return super.getPort(new QName("http://webservices.monditech.com/", "ConsultasSoap"), ConsultasSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultasSoap
     */
    @WebEndpoint(name = "ConsultasSoap")
    public ConsultasSoap getConsultasSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.monditech.com/", "ConsultasSoap"), ConsultasSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAS_EXCEPTION!= null) {
            throw CONSULTAS_EXCEPTION;
        }
        return CONSULTAS_WSDL_LOCATION;
    }

}
